### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by lzm2275965881** [bradyz/cross_view_transformers#23]
I train the model in windows, but there are problems with nccl:
Traceback (most recent call last):
  File "scripts/train.py", line 74, in main
    trainer.fit(model_module, datamodule=data_module, ckpt_path=ckpt_path)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1171, in _run
    self.strategy.setup_environment()
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 152, in setup_environment
    self.setup_distributed()
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 205, in setup_distributed
    init_dist_connection(self.cluster_environment, self._process_group_backend)
  File "D:\anaconda3\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 355, in init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "D:\anaconda3\lib\site-packages\torch\distributed\distributed_c10d.py", line 537, in init_process_group
    default_pg = _new_process_group_helper(
  File "D:\anaconda3\lib\site-packages\torch\distributed\distributed_c10d.py", line 639, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I know that running on windows does not support nccl. So how should I modify it so that I can train normally?

**Comment by bradyz** [comment]
From [https://pytorch.org/docs/stable/distributed.html](https://pytorch.org/docs/stable/distributed.html) it looks like there are some other backends - `gloo` and `mpi`, maybe try passing those for the distributed backend.
